#!/usr/bin/env python3
import sys
import re
import os
import pandas as pd

act = speech = verse = 0
v = [0, 0]
paux = [0, 0]
p = ''
author = title = genre = subgenre = gender = s ='ø'

character = 'STAGE DIR.'
rtag = re.compile(r'^\s*<(.)>')
rtext = re.compile(r'<.>(.*)$')
df = pd.DataFrame(columns=['Author',
                           'Title',
                           'Genre',
                           'Subgenre',
                           'Act',
                           'Speech',
                           'Verse',
                           'Character',
                           'Type',
                           'Gender',
                           'Text'])
names_list = {}


def assign_gender(name):
    name = re.sub(r'(.*)\d.*', '\1', name).strip()
    if name in names_list:
        return names_list[name]
    else:
        if name.endswith('A') or (name.endswith('AS') or
                                    name.endswith('ᵃ') or
                                    name.endswith('ª') or
                                    name.startswith('DOÑA ')):
            sx = 'F'
        elif (name.endswith('O') or name.endswith('OS') or
              name.endswith('°') or name.endswith('º') or
              name.startswith('DON ')):
            sx = 'M'
        else:
            sx = 'X'
    names_list[name] = sx
    return names_list[name]


with open(sys.argv[1], 'r', encoding='utf-8') as f:
    linea = {'Author': '', 'Title': '', 'Genre': '', 'Subgenre': '', 'Act': 0,
             'Speech': 0, 'Verse': 0, 'Character': '', 'Gender': '',
             'Type': '', 'Text': ''}
    for line in f.readlines():
        flag = 1
        if rtag.match(line):
            type_ch = rtag.search(line).group(1)
            text = rtext.search(line).group(1)
            if type_ch.lower() == 'j':
                act += 1
                flag = 0
            elif type_ch.lower() == 't':
                title = text.strip()
                flag = 0
            elif type_ch.lower() == 'a':
                author = text.strip()
                flag = 0
            elif type_ch.lower() == 'g':
                genre = text.strip()
                flag = 0
            elif type_ch.lower() == 's':
                subgenre = text.strip()
                flag = 0
            elif type_ch.lower() == 'i':
                v[1] -= 1
                verse = v[1]
                if line.startswith('\t'):
                    character = 'int. STAGE DIR.'
                else:
                    character = 'STAGE DIR.'
                    speech = paux[1]
                gender = 'ø'
            elif type_ch.lower() in ('p', 'e'):
                verse = 0
                character = p
                gender = s
                text = str(line).strip()
            else:
                verse = 0
                #character = p
                #gender = s
                flag = 0
        else:
            if re.match(r'^\s*$', line):
                flag = 0
            elif not re.match(r'^\t+', line):
                print(speech, paux, paux[0], line)
                p = line.strip().upper()
                paux[0] += 1
                s = assign_gender(p)
                flag = 0
            elif re.match(r'^\t\S', line):
                v[0] += 1
                verse = v[0]
                character = p
                gender = s
            else:
                verse = v[0]
                character = p
                gender = s
            speech = paux[0]
            text = str(line).strip()
        new_line = {'Author': author, 'Title': title, 'Genre': genre,
                      'Subgenre': subgenre, 'Act': act,
                      'Speech': speech, 'Verse': verse,
                      'Character': character, 'Gender': gender, 'Type': '',
                      'Text': text}
        if linea['Verse'] == new_line['Verse']:
            new_line['Character'] == f'{linea["Character"]} y' \
                f'{new_line["Character"]}'
            new_line['Text'] == f'{linea["Text"]} {new_line["Text"]}'
            if new_line['Gender'] != linea['Gender']:
                new_line['Gender'] = f'{linea["Gender"]}' \
                    f'{new_line["Gender"]}'
        linea = new_line
        if flag == 1:
            print(linea)
            df = df.append(linea, ignore_index=True)

df.to_csv(f'{os.path.splitext(sys.argv[1])[0]}.csv', index=False)
